apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wireguard
  name: wireguard-config
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wireguard
  name: wireguard-modules
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

